export const blockedResourceTypes = [
//   'image',
//   'media',
//   'font',
//   'texttrack',
//   'object',
//   'beacon',
//   'csp_report',
//   'imageset',
];

export const skippedResources = [
  'quantserve',
  'adzerk',
  'doubleclick',
  'adition',
  'exelator',
  'sharethrough',
  'cdn.api.twitter',
  'google-analytics',
  'googletagmanager',
  'fontawesome',
  'facebook',
  'analytics',
  'optimizely',
  'clicktale',
  'mixpanel',
  'zedo',
  'clicksor',
  'tiqcdn',
];